# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: your-docker-repo/myapp-image:latest  # Replace with your Docker image details
          ports:
            - containerPort: 10000  # Replace with the gRPC server port of your Go application
