// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: repository/repository.proto

package repository

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	User    string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SearchCodeRequest) Reset() {
	*x = SearchCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repository_repository_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeRequest) ProtoMessage() {}

func (x *SearchCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeRequest.ProtoReflect.Descriptor instead.
func (*SearchCodeRequest) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{0}
}

func (x *SearchCodeRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchCodeRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type SearchCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchCodeResponse) Reset() {
	*x = SearchCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repository_repository_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeResponse) ProtoMessage() {}

func (x *SearchCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_repository_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeResponse.ProtoReflect.Descriptor instead.
func (*SearchCodeResponse) Descriptor() ([]byte, []int) {
	return file_repository_repository_proto_rawDescGZIP(), []int{1}
}

func (x *SearchCodeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_repository_repository_proto protoreflect.FileDescriptor

var file_repository_repository_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x12,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x5b, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x4d, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1d,
	0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x75, 0x73, 0x65, 0x79, 0x69, 0x6e, 0x62, 0x61, 0x62, 0x61, 0x6c, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x69, 0x6e, 0x2d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repository_repository_proto_rawDescOnce sync.Once
	file_repository_repository_proto_rawDescData = file_repository_repository_proto_rawDesc
)

func file_repository_repository_proto_rawDescGZIP() []byte {
	file_repository_repository_proto_rawDescOnce.Do(func() {
		file_repository_repository_proto_rawDescData = protoimpl.X.CompressGZIP(file_repository_repository_proto_rawDescData)
	})
	return file_repository_repository_proto_rawDescData
}

var file_repository_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_repository_repository_proto_goTypes = []interface{}{
	(*SearchCodeRequest)(nil),  // 0: repository.SearchCodeRequest
	(*SearchCodeResponse)(nil), // 1: repository.SearchCodeResponse
}
var file_repository_repository_proto_depIdxs = []int32{
	0, // 0: repository.Repository.Search:input_type -> repository.SearchCodeRequest
	1, // 1: repository.Repository.Search:output_type -> repository.SearchCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repository_repository_proto_init() }
func file_repository_repository_proto_init() {
	if File_repository_repository_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repository_repository_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repository_repository_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repository_repository_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_repository_proto_goTypes,
		DependencyIndexes: file_repository_repository_proto_depIdxs,
		MessageInfos:      file_repository_repository_proto_msgTypes,
	}.Build()
	File_repository_repository_proto = out.File
	file_repository_repository_proto_rawDesc = nil
	file_repository_repository_proto_goTypes = nil
	file_repository_repository_proto_depIdxs = nil
}
